# Generated by Django 5.1.15 on 2026-07-31 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeurs_x', models.JSONField()),
                ('valeurs_y', models.JSONField()),
                ('nombre_series', models.PositiveIntegerField()),
                ('date_acquisition', models.DateTimeField(db_index=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('taille_donnees', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectres', to='echantillons.echantillon')),
            ],
            options={
                'verbose_name': 'Spectre',
                'verbose_name_plural': 'Spectres',
                'db_table': 'spectres_spectre',
                'ordering': ['-date_acquisition'],
            },
        ),
    ]
