# Generated by Django 5.1.15 on 2026-07-31 12:11

import comptes.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('administrateur', 'Administrateur')], db_index=True, default='utilisateur', max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('tentatives_echouees', models.PositiveSmallIntegerField(default=0)),
                ('verrouille_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('token_reset_mot_de_passe_hash', models.CharField(blank=True, default='', max_length=64)),
                ('token_reset_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'comptes_utilisateur',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', comptes.managers.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_actives', models.BooleanField(default=True)),
                ('seuil_conformite_acidite', models.DecimalField(decimal_places=3, max_digits=6)),
                ('seuil_conformite_peroxyde', models.DecimalField(decimal_places=3, max_digits=6)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
                'db_table': 'comptes_configuration',
            },
        ),
    ]
