# Generated by Django 5.1.15 on 2026-08-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='token_reset_expiration',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='token_reset_mot_de_passe_hash',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_reset_demande_fenetre_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_reset_demandes_compteur',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_reset_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_reset_mot_de_passe_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_reset_tentatives_echouees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
