# Generated by Django 5.1.15 on 2026-08-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_configuration_seuils_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='laboratoire',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
