# Generated by Django 5.1.15 on 2026-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echantillons', '0002_echantillon_variete'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_recolte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='producteur',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='region',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
