# Generated by Django 5.1.15 on 2026-07-31 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=50)),
                ('date_analyse', models.DateTimeField(db_index=True)),
                ('origine', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echantillons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Échantillon',
                'verbose_name_plural': 'Échantillons',
                'db_table': 'echantillons_echantillon',
                'ordering': ['-date_analyse'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'numero'), name='echantillon_numero_unique_par_utilisateur')],
            },
        ),
    ]
