# Generated by Django 5.1.15 on 2026-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=30)),
                ('algorithme', models.CharField(max_length=100)),
                ('hyperparametres', models.JSONField(blank=True, default=dict)),
                ('r2', models.FloatField()),
                ('rmsecv', models.FloatField()),
                ('est_actif', models.BooleanField(default=True)),
                ('est_deprecie', models.BooleanField(default=False)),
                ('chemin_fichier', models.CharField(blank=True, default='', max_length=500)),
                ('date_entrainement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'db_table': 'modeles_modele',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'version'), name='modele_nom_version_unique'), models.CheckConstraint(condition=models.Q(('rmsecv__gte', 0)), name='modele_rmsecv_positif')],
            },
        ),
    ]
