# Generated by Django 5.1.15 on 2026-08-07 16:14

import modeles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modele',
            name='chemin_fichier',
        ),
        migrations.AddField(
            model_name='modele',
            name='empreinte_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='modele',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=modeles.models.chemin_upload_modele),
        ),
    ]
