# Generated by Django 5.1.15 on 2026-08-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0002_remove_modele_chemin_fichier_modele_empreinte_sha256_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modele',
            name='modele_rmsecv_positif',
        ),
        migrations.AddField(
            model_name='modele',
            name='est_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modele',
            name='exactitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modele',
            name='grandeur_predite',
            field=models.CharField(choices=[('acidite', 'Acidité'), ('indice_peroxyde', 'Indice de peroxyde'), ('authenticite', 'Authenticité')], default='acidite', max_length=30),
        ),
        migrations.AddField(
            model_name='modele',
            name='precision_classification',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modele',
            name='rappel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modele',
            name='type_modele',
            field=models.CharField(choices=[('regression', 'Régression'), ('classification', 'Classification')], default='regression', max_length=20),
        ),
        migrations.AlterField(
            model_name='modele',
            name='r2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modele',
            name='rmsecv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='modele',
            constraint=models.CheckConstraint(condition=models.Q(('rmsecv__gte', 0), ('rmsecv__isnull', True), _connector='OR'), name='modele_rmsecv_positif'),
        ),
        migrations.AddConstraint(
            model_name='modele',
            constraint=models.UniqueConstraint(condition=models.Q(('est_reference', True)), fields=('grandeur_predite',), name='modele_reference_unique_par_grandeur'),
        ),
    ]
