# Generated by Django 5.1.15 on 2026-07-31 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('seuil_depasse', 'Seuil dépassé'), ('erreur_systeme', 'Erreur système'), ('qualite_donnees', 'Qualité des données')], max_length=30)),
                ('message', models.TextField()),
                ('niveau_gravite', models.CharField(choices=[('info', 'Info'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], db_index=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('est_resolue', models.BooleanField(db_index=True, default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('echantillon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='echantillons.echantillon')),
                ('resolue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_resolues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alertes_alerte',
                'ordering': ['-date_creation'],
            },
        ),
    ]
