# Generated by Django 5.1.15 on 2026-08-13 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0003_remove_modele_modele_rmsecv_positif_and_more'),
        ('resultats', '0002_resultat_duree_analyse_secondes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='acidite_reference',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='authenticite_reference',
            field=models.CharField(blank=True, choices=[('pure', 'Pure'), ('melangee', 'Mélangée')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resultat',
            name='date_mesure_reference',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='indice_peroxyde_reference',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='numero_replicat',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PredictionModele',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur_numerique', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('classe_predite', models.CharField(blank=True, choices=[('pure', 'Pure'), ('melangee', 'Mélangée')], default='', max_length=20)),
                ('score_confiance', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='modeles.modele')),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='resultats.resultat')),
            ],
            options={
                'verbose_name': 'Prédiction de modèle',
                'verbose_name_plural': 'Prédictions de modèles',
                'db_table': 'resultats_prediction_modele',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('resultat', 'modele'), name='prediction_unique_par_resultat_modele')],
            },
        ),
    ]
