# Generated by Django 5.1.15 on 2026-08-14 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('connexion_reussie', 'Connexion réussie'), ('connexion_echouee', 'Connexion échouée'), ('creation_compte', 'Création de compte'), ('changement_role', 'Changement de rôle'), ('activation_compte', 'Activation de compte'), ('desactivation_compte', 'Désactivation de compte'), ('deverrouillage_compte', 'Déverrouillage de compte'), ('reset_mot_de_passe_declenche', 'Réinitialisation de mot de passe déclenchée'), ('modification_configuration', 'Modification de configuration'), ('suppression_modele', 'Suppression de modèle'), ('depreciation_modele', 'Dépréciation de modèle'), ('reactivation_modele', 'Réactivation de modèle'), ('definition_modele_reference', 'Définition du modèle de référence'), ('purge_donnees', 'Purge de données')], db_index=True, max_length=40)),
                ('cible_type', models.CharField(blank=True, default='', max_length=100)),
                ('cible_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée de journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'administration_journal_audit',
                'ordering': ['-date_creation'],
            },
        ),
    ]
