# Generated by Django 5.1.15 on 2026-07-31 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echantillons', '0001_initial'),
        ('modeles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acidite', models.DecimalField(decimal_places=3, max_digits=6)),
                ('indice_peroxyde', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date_calcul', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conforme', models.BooleanField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='echantillons.echantillon')),
                ('modele_utilise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='modeles.modele')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'db_table': 'resultats_resultat',
                'ordering': ['-date_calcul'],
                'constraints': [models.CheckConstraint(condition=models.Q(('acidite__gte', 0), ('indice_peroxyde__gte', 0)), name='resultat_valeurs_positives')],
            },
        ),
    ]
